const ACTION_FILE_ADD = "ACTION_FILE_ADD";
const ACTION_DIR_ADD = "ACTION_DIR_ADD";
const ACTION_FILE_CHANGE = "ACTION_FILE_CHANGE";
const ACTION_DIR_UNLINK = "ACTION_DIR_UNLINK";
const ACTION_FILE_UNLINK = "ACTION_FILE_UNLINK";
const ACTION_CHANGE = "ACTION_CHANGE";
const ACTION_FS_ERROR = "ACTION_FS_ERROR";
const ACTION_FS_INIT = "ACTION_FS_INIT";
const ACTION_WORKSPACE_INFO = "ACTION_FS_INIT";

module.exports = {
 ACTION_FILE_ADD,
 ACTION_DIR_ADD,
 ACTION_FILE_CHANGE,
 ACTION_DIR_UNLINK,
 ACTION_FILE_UNLINK,
 ACTION_CHANGE,
 ACTION_FS_ERROR,
 ACTION_FS_INIT,
 ACTION_WORKSPACE_INFO
}
