const ACTION_FS_FILE_ADD = 'ACTION_FS_FILE_ADD';
const ACTION_FS_DIR_ADD = 'ACTION_FS_DIR_ADD';
const ACTION_FS_FILE_CHANGE = 'ACTION_FS_FILE_CHANGE';
const ACTION_FS_DIR_UNLINK = 'ACTION_FS_DIR_UNLINK';
const ACTION_FS_FILE_UNLINK = 'ACTION_FS_FILE_UNLINK';
const ACTION_FS_CHANGE = 'ACTION_FS_CHANGE';
const ACTION_FS_ERROR = 'ACTION_FS_ERROR';
const ACTION_FS_INIT = 'ACTION_FS_INIT';
const ACTION_FS_WORKSPACE_INFO = 'ACTION_FS_INIT';
const ACTION_FS_LS = 'ACTION_FS_LS';
const ACTION_FS_INFO = 'ACTION_FS_INFO';
const ACTION_FS_CAT = 'ACTION_FS_CAT';
const ACTION_FS_RENAME = 'ACTION_FS_RENAME';

module.exports = {
    ACTION_FS_FILE_ADD,
    ACTION_FS_DIR_ADD,
    ACTION_FS_FILE_CHANGE,
    ACTION_FS_DIR_UNLINK,
    ACTION_FS_FILE_UNLINK,
    ACTION_FS_CHANGE,
    ACTION_FS_ERROR,
    ACTION_FS_INIT,
    ACTION_FS_WORKSPACE_INFO,
    ACTION_FS_LS,
    ACTION_FS_INFO,
    ACTION_FS_CAT,
    ACTION_FS_RENAME,
};


